# Generated by Django 6.0 on 2026-05-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(help_text="Lucide React icon name, e.g. 'Home', 'Shirt'", max_length=100)),
                ('description', models.TextField(help_text='Short description shown in card')),
                ('long_description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text="List of features, e.g. ['Water Resistant', 'Custom Sizes']")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
